name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test build application
        run: yarn build
